### ISSUE TITLE
thread 'main' has overflowed its stack ( recursive imports )

### ISSUE THREAD

**Issue by LowByteFox** [xHyroM/frog#2]
Please fix recursive imports

How to reproduce?

main.frog
```
import "test";

print(ahoj("hyro"));
```

test.frog
```
import "main";

fun ahoj(name) {
    return "ahooojky " + name;
}
```

**Comment by xhyrom** [comment]
Solved by throwing `error:    Circular imports are not allowed, tried to import test.frog`
![image](https://user-images.githubusercontent.com/56601352/200139288-c54919f3-47e9-4a6a-ade6-e2f5932f2815.png)
